apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/AyaELMAFHOUM/deployment.yml.git
    targetRevision: HEAD
    path: .
  project: default
